name: Update TOC

on:
  push:
    branches:
      - main

jobs:
  update-toc:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate TOC
        run: |
          echo "# Table of Contents\n\n" > README.md
          dir /s /b >> README.md
        shell: cmd

      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add README.md
          git diff-index --quiet HEAD || git commit -m "Update TOC"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
